// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MoscowPayphones.InfrastructureServices.Gateways.Database;

namespace MoscowPayphones.WebService.Migrations
{
    [DbContext(typeof(PayphonesContext))]
    partial class PayphonesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4");

            modelBuilder.Entity("MoscowPayphones.DomainObjects.Payphones", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DescriptionLocation")
                        .HasColumnType("TEXT");

                    b.Property<string>("IntercityConnectionPayment")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("PayWay")
                        .HasColumnType("TEXT");

                    b.Property<string>("ValidUniversalServicesCard")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Payphones");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            DescriptionLocation = "Вавилова улица, дом 5А",
                            IntercityConnectionPayment = "бесплатно",
                            Name = "Таксофон № 1449",
                            PayWay = "карта",
                            ValidUniversalServicesCard = "не действует"
                        },
                        new
                        {
                            Id = 2L,
                            DescriptionLocation = "Вавилова улица, дом 51, Школа №199",
                            IntercityConnectionPayment = "бесплатно",
                            Name = "Таксофон № 1499",
                            PayWay = "карта",
                            ValidUniversalServicesCard = "не действует"
                        },
                        new
                        {
                            Id = 3L,
                            DescriptionLocation = "Вавилова улица, дом 6",
                            IntercityConnectionPayment = "бесплатно",
                            Name = "Таксофон № 76",
                            PayWay = "карта",
                            ValidUniversalServicesCard = "не действует"
                        },
                        new
                        {
                            Id = 4L,
                            DescriptionLocation = "Валдайский проезд, дом 14, Школа №158",
                            IntercityConnectionPayment = "бесплатно",
                            Name = "Таксофон № 1857",
                            PayWay = "карта",
                            ValidUniversalServicesCard = "не действует"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
